server:
  port: 8899
spring:
  application:
    name: chaoxingxing
  profiles:
    active: prod
  cloud:
    nacos:
      config:
        file-extension: yml   #指定配置文件扩展名为yml
        password: xujie520.
        server-addr: 183.131.51.137:8848
        username: nacos
        namespace: chaoxing
  config:
    import:
      - nacos:application-${spring.profiles.active}.yml
      - nacos:nacos-discovery.yml

logging:
  
  config: classpath:log4j2-spring-info.xml
  level:
    com.alibaba.cloud.nacos: debug
    com.xujie.business.common.templates: debug
